- name: install payment component
  hosts: payment
  become: yes 
  tasks:
  - name: install python 3.6
    ansible.builtin.yum: 
      name: "{{item}}"
      state: installed
    loop:
    - python36
    - gcc
    - python3-devel

  - name: check roboshop user exits or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: create user roboshop
    become: yes
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0

  - name: check /app directory exists or not 
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: print the directory stats 
    ansible.builtin.debug:
      msg: the directory is {{directory}}

  - name: create /app directory  
    ansible.builtin.file:
      path: /app
      state: directory
    when: directory.stat.exists == false

  - name: download and extract payment
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/payment.zip 
      dest: /app
      remote_src: yes

  - name: install python dependencies 
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args:
      chdir: /app 

  - name: copy payment service to systemd 
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload 
    ansible.builtin.systemd:
      daemon_reload: true

  - name: start and enable payment
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes 
